#!/bin/bash
# Demo workflow for Chris

echo "=== Little Snitch Rule Generator Workflow Demo ==="
echo ""
echo "1. CURRENTLY CONFIGURED:"
echo "   ✅ 30 coding harness process paths (desktop and CLI)"
echo "   ✅ 82 domains extracted from your Little Snitch rules"
echo "   ✅ 2,460 rules generated (30×82)"
echo ""
echo "2. Subscribe in Little Snitch:"
echo "   https://[your-github-username].github.io/collection-lsrules/generated/coding.lsrules"
echo ""
echo "3. Add new app later:"
echo "   Edit config/paths.json with executable path"
echo "   Commit → GitHub Action auto-regenerates rules"
echo "   Little Snitch auto-updates via subscription"
echo ""
echo "4. Add new domains:"
echo "   Copy Little Snitch output to clipboard"
echo "   Run: pbpaste | npm run merge-remotes"
echo "   Or use VS Code task: \"Merge Domains from Clipboard\""
echo ""
echo "=== Current Status ==="
echo "Paths configured: $(grep -c '"name":' config/paths.json)"
echo "Remotes configured: $(node -e "const r=require('./config/remotes.json'); console.log(r.domains.length + r.hosts.length)")"
echo "Rules in coding.lsrules: $(grep -c '"priority": "regular"' generated/coding.lsrules 2>/dev/null || echo 'Not generated yet')"
echo "File size: $(ls -lh generated/coding.lsrules 2>/dev/null | awk '{print $5}' || echo 'N/A')"
echo ""
echo "To test: npm run generate"
